apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    tags.datadoghq.com/env: learn-golang
    tags.datadoghq.com/service: golang-app
    tags.datadoghq.com/version: 1.0.0
  name: golang-app
  namespace: learn-golang
spec:
  replicas: 1
  selector:
    matchLabels:
      app: golang-app
  template:
    metadata:
      labels:
        admission.datadoghq.com/enabled: "true"      
        app: golang-app
        tags.datadoghq.com/env: learn-golang
        tags.datadoghq.com/service: golang-app
        tags.datadoghq.com/version: 1.0.0
    spec:
      containers:
      - name: golang-app
        image: jonlimpw/learn-golang:latest
        imagePullPolicy: Always
        env:
        - name: DD_TRACE_DEBUG
          value: "true"
        - name: DD_AGENT_HOST
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP                
        ports:
        - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: golang-service
  namespace: learn-golang
spec:
  selector:
    app: golang-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
